name: conference

services:
  sound_server:
    build: ./server

  redis_sound:
    image: "redis:alpine"

  redis_info:
    image: "redis:alpine"

  files_server:
    build: ./restServer
    ports:
      - "8086:8086"

  nginx:
    image: "nginx"
    volumes:
      -  ${HTML_PATH}:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl.conf:/etc/nginx/conf.d/ssl.conf
    ports:
      - "443:443"

  envoy:
    image: "envoyproxy/envoy-dev:c11574972860a40de36acf3ab8d930273f5ece65"
    volumes:
      - ./envoy-override.yaml:/envoy-override.yaml
    command: -c /envoy-override.yaml
